// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/weather/v1/weather.proto

package weatherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WeatherCondition enumerates the possible derived sky/precipitation conditions.
// Values are ordered by specificity: precipitation > night > sky cover.
type WeatherCondition int32

const (
	WeatherCondition_WEATHER_CONDITION_UNSPECIFIED   WeatherCondition = 0
	WeatherCondition_WEATHER_CONDITION_SUNNY         WeatherCondition = 1
	WeatherCondition_WEATHER_CONDITION_MOSTLY_SUNNY  WeatherCondition = 2
	WeatherCondition_WEATHER_CONDITION_PARTLY_CLOUDY WeatherCondition = 3
	WeatherCondition_WEATHER_CONDITION_MOSTLY_CLOUDY WeatherCondition = 4
	WeatherCondition_WEATHER_CONDITION_OVERCAST      WeatherCondition = 5
	WeatherCondition_WEATHER_CONDITION_LIGHT_RAIN    WeatherCondition = 6
	WeatherCondition_WEATHER_CONDITION_RAIN          WeatherCondition = 7
	WeatherCondition_WEATHER_CONDITION_HEAVY_RAIN    WeatherCondition = 8
	WeatherCondition_WEATHER_CONDITION_FREEZING_RAIN WeatherCondition = 9
	WeatherCondition_WEATHER_CONDITION_SNOW          WeatherCondition = 10
	WeatherCondition_WEATHER_CONDITION_NIGHT         WeatherCondition = 11
)

// Enum value maps for WeatherCondition.
var (
	WeatherCondition_name = map[int32]string{
		0:  "WEATHER_CONDITION_UNSPECIFIED",
		1:  "WEATHER_CONDITION_SUNNY",
		2:  "WEATHER_CONDITION_MOSTLY_SUNNY",
		3:  "WEATHER_CONDITION_PARTLY_CLOUDY",
		4:  "WEATHER_CONDITION_MOSTLY_CLOUDY",
		5:  "WEATHER_CONDITION_OVERCAST",
		6:  "WEATHER_CONDITION_LIGHT_RAIN",
		7:  "WEATHER_CONDITION_RAIN",
		8:  "WEATHER_CONDITION_HEAVY_RAIN",
		9:  "WEATHER_CONDITION_FREEZING_RAIN",
		10: "WEATHER_CONDITION_SNOW",
		11: "WEATHER_CONDITION_NIGHT",
	}
	WeatherCondition_value = map[string]int32{
		"WEATHER_CONDITION_UNSPECIFIED":   0,
		"WEATHER_CONDITION_SUNNY":         1,
		"WEATHER_CONDITION_MOSTLY_SUNNY":  2,
		"WEATHER_CONDITION_PARTLY_CLOUDY": 3,
		"WEATHER_CONDITION_MOSTLY_CLOUDY": 4,
		"WEATHER_CONDITION_OVERCAST":      5,
		"WEATHER_CONDITION_LIGHT_RAIN":    6,
		"WEATHER_CONDITION_RAIN":          7,
		"WEATHER_CONDITION_HEAVY_RAIN":    8,
		"WEATHER_CONDITION_FREEZING_RAIN": 9,
		"WEATHER_CONDITION_SNOW":          10,
		"WEATHER_CONDITION_NIGHT":         11,
	}
)

func (x WeatherCondition) Enum() *WeatherCondition {
	p := new(WeatherCondition)
	*p = x
	return p
}

func (x WeatherCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeatherCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_weather_v1_weather_proto_enumTypes[0].Descriptor()
}

func (WeatherCondition) Type() protoreflect.EnumType {
	return &file_proto_weather_v1_weather_proto_enumTypes[0]
}

func (x WeatherCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeatherCondition.Descriptor instead.
func (WeatherCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

type WeatherReading struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TempC          float64                `protobuf:"fixed64,2,opt,name=temp_c,json=tempC,proto3" json:"temp_c,omitempty"`
	HumidityPct    float64                `protobuf:"fixed64,3,opt,name=humidity_pct,json=humidityPct,proto3" json:"humidity_pct,omitempty"`
	PressureHpa    float64                `protobuf:"fixed64,4,opt,name=pressure_hpa,json=pressureHpa,proto3" json:"pressure_hpa,omitempty"`
	WindSpeedMs    float64                `protobuf:"fixed64,5,opt,name=wind_speed_ms,json=windSpeedMs,proto3" json:"wind_speed_ms,omitempty"`
	WindDirDeg     float64                `protobuf:"fixed64,6,opt,name=wind_dir_deg,json=windDirDeg,proto3" json:"wind_dir_deg,omitempty"`
	RainMmHr       float64                `protobuf:"fixed64,7,opt,name=rain_mm_hr,json=rainMmHr,proto3" json:"rain_mm_hr,omitempty"`
	UvIndex        float64                `protobuf:"fixed64,8,opt,name=uv_index,json=uvIndex,proto3" json:"uv_index,omitempty"`
	SolarWm2       float64                `protobuf:"fixed64,9,opt,name=solar_wm2,json=solarWm2,proto3" json:"solar_wm2,omitempty"`
	RainEventMm    float64                `protobuf:"fixed64,10,opt,name=rain_event_mm,json=rainEventMm,proto3" json:"rain_event_mm,omitempty"`
	RainYearlyMm   float64                `protobuf:"fixed64,11,opt,name=rain_yearly_mm,json=rainYearlyMm,proto3" json:"rain_yearly_mm,omitempty"`
	WindGustMs     float64                `protobuf:"fixed64,12,opt,name=wind_gust_ms,json=windGustMs,proto3" json:"wind_gust_ms,omitempty"`
	RainDailyMm    float64                `protobuf:"fixed64,13,opt,name=rain_daily_mm,json=rainDailyMm,proto3" json:"rain_daily_mm,omitempty"`
	RainWeeklyMm   float64                `protobuf:"fixed64,14,opt,name=rain_weekly_mm,json=rainWeeklyMm,proto3" json:"rain_weekly_mm,omitempty"`
	RainMonthlyMm  float64                `protobuf:"fixed64,15,opt,name=rain_monthly_mm,json=rainMonthlyMm,proto3" json:"rain_monthly_mm,omitempty"`
	PressureAbsHpa float64                `protobuf:"fixed64,16,opt,name=pressure_abs_hpa,json=pressureAbsHpa,proto3" json:"pressure_abs_hpa,omitempty"`
	TempInC        float64                `protobuf:"fixed64,17,opt,name=temp_in_c,json=tempInC,proto3" json:"temp_in_c,omitempty"`
	HumidityInPct  float64                `protobuf:"fixed64,18,opt,name=humidity_in_pct,json=humidityInPct,proto3" json:"humidity_in_pct,omitempty"`
	MaxDailyGustMs float64                `protobuf:"fixed64,19,opt,name=max_daily_gust_ms,json=maxDailyGustMs,proto3" json:"max_daily_gust_ms,omitempty"`
	RainHourlyMm   float64                `protobuf:"fixed64,20,opt,name=rain_hourly_mm,json=rainHourlyMm,proto3" json:"rain_hourly_mm,omitempty"`
	BatteryV       float64                `protobuf:"fixed64,22,opt,name=battery_v,json=batteryV,proto3" json:"battery_v,omitempty"`
	CapacitorV     float64                `protobuf:"fixed64,23,opt,name=capacitor_v,json=capacitorV,proto3" json:"capacitor_v,omitempty"`
	// Derived atmospheric fields.
	DewPointC float64 `protobuf:"fixed64,27,opt,name=dew_point_c,json=dewPointC,proto3" json:"dew_point_c,omitempty"` // Magnus formula from temp_c + humidity_pct
	// Derived solar fields — computed from solar_wm2 and station location.
	ClearSkyWm2   float64 `protobuf:"fixed64,24,opt,name=clear_sky_wm2,json=clearSkyWm2,proto3" json:"clear_sky_wm2,omitempty"`       // theoretical clear-sky GHI (W/m²)
	ClearSkyIndex float64 `protobuf:"fixed64,25,opt,name=clear_sky_index,json=clearSkyIndex,proto3" json:"clear_sky_index,omitempty"` // Kt = measured / clear-sky; 0 when sun below horizon
	CloudCoverPct float64 `protobuf:"fixed64,26,opt,name=cloud_cover_pct,json=cloudCoverPct,proto3" json:"cloud_cover_pct,omitempty"` // estimated cloud cover 0–100 %; -1 when sun below horizon
	// Derived situational — derived from the fields above.
	// feels_like_c is stored; condition is never persisted to InfluxDB.
	FeelsLikeC    float64          `protobuf:"fixed64,29,opt,name=feels_like_c,json=feelsLikeC,proto3" json:"feels_like_c,omitempty"` // EC wind-chill or humidex (°C); equals temp_c when neither applies
	Condition     WeatherCondition `protobuf:"varint,28,opt,name=condition,proto3,enum=weather.v1.WeatherCondition" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherReading) Reset() {
	*x = WeatherReading{}
	mi := &file_proto_weather_v1_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherReading) ProtoMessage() {}

func (x *WeatherReading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_v1_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherReading.ProtoReflect.Descriptor instead.
func (*WeatherReading) Descriptor() ([]byte, []int) {
	return file_proto_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherReading) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WeatherReading) GetTempC() float64 {
	if x != nil {
		return x.TempC
	}
	return 0
}

func (x *WeatherReading) GetHumidityPct() float64 {
	if x != nil {
		return x.HumidityPct
	}
	return 0
}

func (x *WeatherReading) GetPressureHpa() float64 {
	if x != nil {
		return x.PressureHpa
	}
	return 0
}

func (x *WeatherReading) GetWindSpeedMs() float64 {
	if x != nil {
		return x.WindSpeedMs
	}
	return 0
}

func (x *WeatherReading) GetWindDirDeg() float64 {
	if x != nil {
		return x.WindDirDeg
	}
	return 0
}

func (x *WeatherReading) GetRainMmHr() float64 {
	if x != nil {
		return x.RainMmHr
	}
	return 0
}

func (x *WeatherReading) GetUvIndex() float64 {
	if x != nil {
		return x.UvIndex
	}
	return 0
}

func (x *WeatherReading) GetSolarWm2() float64 {
	if x != nil {
		return x.SolarWm2
	}
	return 0
}

func (x *WeatherReading) GetRainEventMm() float64 {
	if x != nil {
		return x.RainEventMm
	}
	return 0
}

func (x *WeatherReading) GetRainYearlyMm() float64 {
	if x != nil {
		return x.RainYearlyMm
	}
	return 0
}

func (x *WeatherReading) GetWindGustMs() float64 {
	if x != nil {
		return x.WindGustMs
	}
	return 0
}

func (x *WeatherReading) GetRainDailyMm() float64 {
	if x != nil {
		return x.RainDailyMm
	}
	return 0
}

func (x *WeatherReading) GetRainWeeklyMm() float64 {
	if x != nil {
		return x.RainWeeklyMm
	}
	return 0
}

func (x *WeatherReading) GetRainMonthlyMm() float64 {
	if x != nil {
		return x.RainMonthlyMm
	}
	return 0
}

func (x *WeatherReading) GetPressureAbsHpa() float64 {
	if x != nil {
		return x.PressureAbsHpa
	}
	return 0
}

func (x *WeatherReading) GetTempInC() float64 {
	if x != nil {
		return x.TempInC
	}
	return 0
}

func (x *WeatherReading) GetHumidityInPct() float64 {
	if x != nil {
		return x.HumidityInPct
	}
	return 0
}

func (x *WeatherReading) GetMaxDailyGustMs() float64 {
	if x != nil {
		return x.MaxDailyGustMs
	}
	return 0
}

func (x *WeatherReading) GetRainHourlyMm() float64 {
	if x != nil {
		return x.RainHourlyMm
	}
	return 0
}

func (x *WeatherReading) GetBatteryV() float64 {
	if x != nil {
		return x.BatteryV
	}
	return 0
}

func (x *WeatherReading) GetCapacitorV() float64 {
	if x != nil {
		return x.CapacitorV
	}
	return 0
}

func (x *WeatherReading) GetDewPointC() float64 {
	if x != nil {
		return x.DewPointC
	}
	return 0
}

func (x *WeatherReading) GetClearSkyWm2() float64 {
	if x != nil {
		return x.ClearSkyWm2
	}
	return 0
}

func (x *WeatherReading) GetClearSkyIndex() float64 {
	if x != nil {
		return x.ClearSkyIndex
	}
	return 0
}

func (x *WeatherReading) GetCloudCoverPct() float64 {
	if x != nil {
		return x.CloudCoverPct
	}
	return 0
}

func (x *WeatherReading) GetFeelsLikeC() float64 {
	if x != nil {
		return x.FeelsLikeC
	}
	return 0
}

func (x *WeatherReading) GetCondition() WeatherCondition {
	if x != nil {
		return x.Condition
	}
	return WeatherCondition_WEATHER_CONDITION_UNSPECIFIED
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_weather_v1_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_v1_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_weather_v1_weather_proto_rawDescGZIP(), []int{1}
}

type RainAccumulationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// end is optional; server uses current time if zero.
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RainAccumulationRequest) Reset() {
	*x = RainAccumulationRequest{}
	mi := &file_proto_weather_v1_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RainAccumulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RainAccumulationRequest) ProtoMessage() {}

func (x *RainAccumulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_v1_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RainAccumulationRequest.ProtoReflect.Descriptor instead.
func (*RainAccumulationRequest) Descriptor() ([]byte, []int) {
	return file_proto_weather_v1_weather_proto_rawDescGZIP(), []int{2}
}

func (x *RainAccumulationRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RainAccumulationRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type RainAccumulationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Accumulated rainfall in mm (last rain_yearly_mm minus first over the range).
	RainMm float64 `protobuf:"fixed64,1,opt,name=rain_mm,json=rainMm,proto3" json:"rain_mm,omitempty"`
	// Timestamps of the actual first and last data points found.
	ActualStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=actual_start,json=actualStart,proto3" json:"actual_start,omitempty"`
	ActualEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=actual_end,json=actualEnd,proto3" json:"actual_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RainAccumulationResponse) Reset() {
	*x = RainAccumulationResponse{}
	mi := &file_proto_weather_v1_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RainAccumulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RainAccumulationResponse) ProtoMessage() {}

func (x *RainAccumulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_v1_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RainAccumulationResponse.ProtoReflect.Descriptor instead.
func (*RainAccumulationResponse) Descriptor() ([]byte, []int) {
	return file_proto_weather_v1_weather_proto_rawDescGZIP(), []int{3}
}

func (x *RainAccumulationResponse) GetRainMm() float64 {
	if x != nil {
		return x.RainMm
	}
	return 0
}

func (x *RainAccumulationResponse) GetActualStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualStart
	}
	return nil
}

func (x *RainAccumulationResponse) GetActualEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualEnd
	}
	return nil
}

var File_proto_weather_v1_weather_proto protoreflect.FileDescriptor

const file_proto_weather_v1_weather_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/weather/v1/weather.proto\x12\n" +
	"weather.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\b\n" +
	"\x0eWeatherReading\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x15\n" +
	"\x06temp_c\x18\x02 \x01(\x01R\x05tempC\x12!\n" +
	"\fhumidity_pct\x18\x03 \x01(\x01R\vhumidityPct\x12!\n" +
	"\fpressure_hpa\x18\x04 \x01(\x01R\vpressureHpa\x12\"\n" +
	"\rwind_speed_ms\x18\x05 \x01(\x01R\vwindSpeedMs\x12 \n" +
	"\fwind_dir_deg\x18\x06 \x01(\x01R\n" +
	"windDirDeg\x12\x1c\n" +
	"\n" +
	"rain_mm_hr\x18\a \x01(\x01R\brainMmHr\x12\x19\n" +
	"\buv_index\x18\b \x01(\x01R\auvIndex\x12\x1b\n" +
	"\tsolar_wm2\x18\t \x01(\x01R\bsolarWm2\x12\"\n" +
	"\rrain_event_mm\x18\n" +
	" \x01(\x01R\vrainEventMm\x12$\n" +
	"\x0erain_yearly_mm\x18\v \x01(\x01R\frainYearlyMm\x12 \n" +
	"\fwind_gust_ms\x18\f \x01(\x01R\n" +
	"windGustMs\x12\"\n" +
	"\rrain_daily_mm\x18\r \x01(\x01R\vrainDailyMm\x12$\n" +
	"\x0erain_weekly_mm\x18\x0e \x01(\x01R\frainWeeklyMm\x12&\n" +
	"\x0frain_monthly_mm\x18\x0f \x01(\x01R\rrainMonthlyMm\x12(\n" +
	"\x10pressure_abs_hpa\x18\x10 \x01(\x01R\x0epressureAbsHpa\x12\x1a\n" +
	"\ttemp_in_c\x18\x11 \x01(\x01R\atempInC\x12&\n" +
	"\x0fhumidity_in_pct\x18\x12 \x01(\x01R\rhumidityInPct\x12)\n" +
	"\x11max_daily_gust_ms\x18\x13 \x01(\x01R\x0emaxDailyGustMs\x12$\n" +
	"\x0erain_hourly_mm\x18\x14 \x01(\x01R\frainHourlyMm\x12\x1b\n" +
	"\tbattery_v\x18\x16 \x01(\x01R\bbatteryV\x12\x1f\n" +
	"\vcapacitor_v\x18\x17 \x01(\x01R\n" +
	"capacitorV\x12\x1e\n" +
	"\vdew_point_c\x18\x1b \x01(\x01R\tdewPointC\x12\"\n" +
	"\rclear_sky_wm2\x18\x18 \x01(\x01R\vclearSkyWm2\x12&\n" +
	"\x0fclear_sky_index\x18\x19 \x01(\x01R\rclearSkyIndex\x12&\n" +
	"\x0fcloud_cover_pct\x18\x1a \x01(\x01R\rcloudCoverPct\x12 \n" +
	"\ffeels_like_c\x18\x1d \x01(\x01R\n" +
	"feelsLikeC\x12:\n" +
	"\tcondition\x18\x1c \x01(\x0e2\x1c.weather.v1.WeatherConditionR\tconditionJ\x04\b\x15\x10\x16R\x0erain_season_mm\"\x0f\n" +
	"\rStreamRequest\"y\n" +
	"\x17RainAccumulationRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xad\x01\n" +
	"\x18RainAccumulationResponse\x12\x17\n" +
	"\arain_mm\x18\x01 \x01(\x01R\x06rainMm\x12=\n" +
	"\factual_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vactualStart\x129\n" +
	"\n" +
	"actual_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tactualEnd*\x9e\x03\n" +
	"\x10WeatherCondition\x12!\n" +
	"\x1dWEATHER_CONDITION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WEATHER_CONDITION_SUNNY\x10\x01\x12\"\n" +
	"\x1eWEATHER_CONDITION_MOSTLY_SUNNY\x10\x02\x12#\n" +
	"\x1fWEATHER_CONDITION_PARTLY_CLOUDY\x10\x03\x12#\n" +
	"\x1fWEATHER_CONDITION_MOSTLY_CLOUDY\x10\x04\x12\x1e\n" +
	"\x1aWEATHER_CONDITION_OVERCAST\x10\x05\x12 \n" +
	"\x1cWEATHER_CONDITION_LIGHT_RAIN\x10\x06\x12\x1a\n" +
	"\x16WEATHER_CONDITION_RAIN\x10\a\x12 \n" +
	"\x1cWEATHER_CONDITION_HEAVY_RAIN\x10\b\x12#\n" +
	"\x1fWEATHER_CONDITION_FREEZING_RAIN\x10\t\x12\x1a\n" +
	"\x16WEATHER_CONDITION_SNOW\x10\n" +
	"\x12\x1b\n" +
	"\x17WEATHER_CONDITION_NIGHT\x10\v2\xbf\x01\n" +
	"\x0eWeatherService\x12I\n" +
	"\x0eStreamReadings\x12\x19.weather.v1.StreamRequest\x1a\x1a.weather.v1.WeatherReading0\x01\x12b\n" +
	"\x15QueryRainAccumulation\x12#.weather.v1.RainAccumulationRequest\x1a$.weather.v1.RainAccumulationResponseBAZ?github.com/rmrobinson/weather-server/proto/weather/v1;weatherv1b\x06proto3"

var (
	file_proto_weather_v1_weather_proto_rawDescOnce sync.Once
	file_proto_weather_v1_weather_proto_rawDescData []byte
)

func file_proto_weather_v1_weather_proto_rawDescGZIP() []byte {
	file_proto_weather_v1_weather_proto_rawDescOnce.Do(func() {
		file_proto_weather_v1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_weather_v1_weather_proto_rawDesc), len(file_proto_weather_v1_weather_proto_rawDesc)))
	})
	return file_proto_weather_v1_weather_proto_rawDescData
}

var file_proto_weather_v1_weather_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_weather_v1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_weather_v1_weather_proto_goTypes = []any{
	(WeatherCondition)(0),            // 0: weather.v1.WeatherCondition
	(*WeatherReading)(nil),           // 1: weather.v1.WeatherReading
	(*StreamRequest)(nil),            // 2: weather.v1.StreamRequest
	(*RainAccumulationRequest)(nil),  // 3: weather.v1.RainAccumulationRequest
	(*RainAccumulationResponse)(nil), // 4: weather.v1.RainAccumulationResponse
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_proto_weather_v1_weather_proto_depIdxs = []int32{
	5, // 0: weather.v1.WeatherReading.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: weather.v1.WeatherReading.condition:type_name -> weather.v1.WeatherCondition
	5, // 2: weather.v1.RainAccumulationRequest.start:type_name -> google.protobuf.Timestamp
	5, // 3: weather.v1.RainAccumulationRequest.end:type_name -> google.protobuf.Timestamp
	5, // 4: weather.v1.RainAccumulationResponse.actual_start:type_name -> google.protobuf.Timestamp
	5, // 5: weather.v1.RainAccumulationResponse.actual_end:type_name -> google.protobuf.Timestamp
	2, // 6: weather.v1.WeatherService.StreamReadings:input_type -> weather.v1.StreamRequest
	3, // 7: weather.v1.WeatherService.QueryRainAccumulation:input_type -> weather.v1.RainAccumulationRequest
	1, // 8: weather.v1.WeatherService.StreamReadings:output_type -> weather.v1.WeatherReading
	4, // 9: weather.v1.WeatherService.QueryRainAccumulation:output_type -> weather.v1.RainAccumulationResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_weather_v1_weather_proto_init() }
func file_proto_weather_v1_weather_proto_init() {
	if File_proto_weather_v1_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_weather_v1_weather_proto_rawDesc), len(file_proto_weather_v1_weather_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weather_v1_weather_proto_goTypes,
		DependencyIndexes: file_proto_weather_v1_weather_proto_depIdxs,
		EnumInfos:         file_proto_weather_v1_weather_proto_enumTypes,
		MessageInfos:      file_proto_weather_v1_weather_proto_msgTypes,
	}.Build()
	File_proto_weather_v1_weather_proto = out.File
	file_proto_weather_v1_weather_proto_goTypes = nil
	file_proto_weather_v1_weather_proto_depIdxs = nil
}
